CASE INSENSITIVE FILE"SYSTEM"S STRIKE AGAIN
$ "/etc" | path relative-to "/Etc"

Error: nu::shell::cant_convert

  × Can't convert to prefix not found.
   ╭─[entry #8:1:1]
 1 │ "/etc" | path relative-to "/Etc"
   · ───┬──
   ·    ╰── can't convert string to prefix not found
   ╰────

FUCK FUCK FUCK FUCK FUCK FUCK FUCK

CURSE YOU APFS
CURSE YOU APPLE

CAN A MAN NOT HAVE GOOD SOFTWARE?